const EstadoPedido = Object.freeze({ /*ENUM*/
    PENDIENTE:"PENDIENTE",
    CONFIRMADO:"CONFIRMADO",
    EN_PREPARACION:"EN_PREPARACION",
    ENVIADO:"ENVIADO",
    ENTREGADO:"ENTREGADO",
    CANCELADO:"CANCELADO"
})